services:
  cfs:
    build:
      context: . .
      dockerfile: ./Dockerfile
    ports:
      - "3939:3939"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared-network
      - postgres-network
    volumes:
      - /volumes/cfs

  db:
    container_name: db
    networks:
      - postgres-network
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PG_TRUST_LOCALNET: 1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "db", "-U", "db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
networks:
  postgres-network:
    driver: bridge
  shared-network:
    external: true
volumes:
  pgdata: